// This file is auto-generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.
// Your Firebase configuration for this project.
export const firebaseConfig = {
  projectId: "studio-1080409365-de71d",
  appId: "1:202121218140:web:48b06ef99af2cc05f73e99",
  apiKey: "AIzaSyA_2IDFJNQcJCuAHKp3InqlkBucBxv69XY",
  authDomain: "studio-1080409365-de71d.firebaseapp.com",
  measurementId: "",
  messagingSenderId: "202121218140",
  storageBucket: "studio-1080409365-de71d.appspot.com",
};
